use std::{
    env,
    fs::{self},
    path::{Path, PathBuf},
    process::Command,
};

fn main() {
    let arch = env::var("CARGO_CFG_TARGET_ARCH")
        .expect("CARGO_CFG_TARGET_ARCH not set");

    let linker_script = format!("linker-{arch}.ld");
    println!("cargo:rustc-link-arg=-T{linker_script}");
    println!("cargo:rerun-if-changed={linker_script}");

    let src_dir = Path::new("src");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let mut object_files = Vec::new();

    visit_dir(src_dir, &mut |path| {
        if path.extension().and_then(|e| e.to_str()) == Some("asm") {
            let obj = compile_nasm(path, &out_dir);
            object_files.push(obj);
        }
    });

    if !object_files.is_empty() {
        let lib_path = out_dir.join("libasm.a");
        archive_objects(&lib_path, &object_files);

        println!("cargo:rustc-link-search={}", out_dir.display());
        println!("cargo:rustc-link-lib=static=asm");
    }

    generate_version_file(&out_dir);
}

fn generate_version_file(out_dir: &Path) {
    let pkg_name = env::var("CARGO_PKG_NAME").unwrap_or_else(|_| "kernel".into());
    let version = env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".into());
    let profile = env::var("PROFILE").unwrap_or_else(|_| "unknown".into());

    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_else(|_| "unknown".into());
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_else(|_| "unknown".into());
    let target_env = env::var("CARGO_CFG_TARGET_ENV").unwrap_or_else(|_| "unknown".into());
    let target_triple = env::var("TARGET").unwrap_or_else(|_| "unknown".into());

    let git_hash = get_git_hash().unwrap_or_else(|| "nogit".into());
    let git_branch = get_git_branch().unwrap_or_else(|| "detached".into());

    let rustc_version = get_rustc_version().unwrap_or_else(|| "unknown".into());

    let build_date = {
        use std::time::{SystemTime, UNIX_EPOCH};
        let secs = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();
        secs.to_string()
    };

    let (major, minor, patch, suffix) = parse_version(&version);

    let content = format!(
r#"// AUTOGENERATED — DO NOT EDIT

pub const KERNEL_NAME: &str = "{pkg_name}";
pub const KERNEL_VERSION: &str = "{version}";

pub const KERNEL_VERSION_MAJOR: u32 = {major};
pub const KERNEL_VERSION_MINOR: u32 = {minor};
pub const KERNEL_VERSION_PATCH: u32 = {patch};
pub const KERNEL_VERSION_SUFFIX: &str = "{suffix}";

pub const BUILD_UNIX_TIME: &str = "{build_date}";
pub const BUILD_PROFILE: &str = "{profile}";

pub const GIT_HASH: &str = "{git_hash}";
pub const GIT_BRANCH: &str = "{git_branch}";

pub const RUSTC_VERSION: &str = "{rustc_version}";

pub const TARGET_ARCH: &str = "{target_arch}";
pub const TARGET_OS: &str = "{target_os}";
pub const TARGET_ENV: &str = "{target_env}";
pub const TARGET_TRIPLE: &str = "{target_triple}";

pub const KERNEL_VERSION_FULL: &str =
    "{pkg_name} {version} ({target_triple}, {profile})";
"#);

    let path = out_dir.join("kernel_version.rs");
    std::fs::write(&path, content).expect("write kernel_version.rs");

    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=.git/HEAD");
}

fn parse_version(v: &str) -> (u32, u32, u32, String) {
    let mut main = v;
    let mut suffix = "";

    if let Some((a, b)) = v.split_once('-') {
        main = a;
        suffix = b;
    }

    let mut it = main.split('.');
    let major = it.next().and_then(|x| x.parse().ok()).unwrap_or(0);
    let minor = it.next().and_then(|x| x.parse().ok()).unwrap_or(0);
    let patch = it.next().and_then(|x| x.parse().ok()).unwrap_or(0);

    (major, minor, patch, suffix.into())
}

fn get_rustc_version() -> Option<String> {
    Command::new("rustc")
        .arg("--version")
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().into())
}

fn get_git_hash() -> Option<String> {
    Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .and_then(|output| {
            if output.status.success() {
                String::from_utf8(output.stdout).ok().map(|s| s.trim().to_string())
            } else {
                None
            }
        })
}

fn get_git_branch() -> Option<String> {
    Command::new("git")
        .args(["rev-parse", "--abbrev-ref", "HEAD"])
        .output()
        .ok()
        .and_then(|output| {
            if output.status.success() {
                String::from_utf8(output.stdout).ok().map(|s| s.trim().to_string())
            } else {
                None
            }
        })
}

fn visit_dir(dir: &Path, f: &mut impl FnMut(&Path)) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            println!("cargo:rerun-if-changed={}", path.display());

            if path.is_dir() {
                visit_dir(&path, f);
            } else {
                f(&path);
            }
        }
    }
}

fn compile_nasm(src: &Path, out_dir: &Path) -> PathBuf {
    let obj = out_dir.join(
        src.file_stem()
            .expect("bad asm filename")
            .to_str()
            .unwrap()
            .to_owned() + ".o",
    );

    let status = Command::new("nasm")
        .args([
            "-f", "elf64",
            "-g", "-F", "dwarf", 
            src.to_str().unwrap(),
            "-o",
            obj.to_str().unwrap(),
        ])
        .status()
        .expect("failed to run nasm");

    assert!(
        status.success(),
        "NASM failed on {}",
        src.display()
    );

    obj
}

fn archive_objects(lib: &Path, objects: &[PathBuf]) {
    let mut cmd = Command::new("ar");
    cmd.args(["crs", lib.to_str().unwrap()]);

    for obj in objects {
        cmd.arg(obj);
    }

    let status = cmd.status().expect("failed to run ar");
    assert!(status.success(), "ar failed");
}